image: node:14

clone:
  depth: full

pipelines:
  pull-requests:
    '**':
      - step:
          name: Lint, Format & Test
          caches:
            - node
          script:
            - yarn install
            - yarn format:check
            - yarn lint:check
            - yarn test

  branches:
    main:
      - step:
          name: Lint, Format, Test & Build
          caches:
            - node
          script:
            - yarn install
            - yarn format:check
            - yarn lint:check
            - yarn test
            - yarn build
          artifacts:
            - storybook-static/**
            - packages/**/build/**

      - step:
          name: Deploy to acceptance
          deployment: acceptance
          script:
            - yarn deploy:acceptance

      - step:
          name: Deploy to production
          deployment: production
          trigger: 'manual'
          script:
            - yarn deploy
