image: node:14

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build, Format & Lint checks
          caches:
            - node
          script:
            - yarn install
            - yarn format:check
            - yarn lint:check

  branches:
    main:
      - step:
          name: Build, Format & Lint checks
          caches:
            - node
          script:
            - yarn install
            - yarn format:check
            - yarn lint:check
