image: node:14

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build & Test
          caches:
            - node
          script:
            - yarn install
            - yarn format:check
            - yarn lint:check
            - yarn test

  branches:
    main:
      - step:
          name: Build & Test
          caches:
            - node
          script:
            - yarn install
            - yarn format:check
            - yarn lint:check
            - yarn test
