image: node:14

pipelines:
  pull-requests:
    '**':
      - parallel:
          - step:
              name: Format check
              script:
                - yarn format:check
          - step:
              name: Lint check
              script:
                - yarn lint:check
