import { TypographyVariant, TypographySettings } from './Typography.types';

export const typographyConfig: Record<TypographyVariant, TypographySettings> = {
  // Headings
  h1: {
    fontFamily: 'BaselineFontFontFamilyPoppinsSemiBold',
    fontSize: 'BaselineFontFontSize32',
    lineHeight: 'BaselineFontFontSize46',
    fontWeight: 'BaselineFontFontWeightSemiBold',
    responsiveFontSize: 'BaselineFontFontSize28',
    responsiveLineHeight: 'BaselineFontFontSize42',
    semanticTag: 'h1',
  },
  h2: {
    fontFamily: 'BaselineFontFontFamilyPoppinsSemiBold',
    fontSize: 'BaselineFontFontSize22',
    lineHeight: 'BaselineFontFontSize38',
    fontWeight: 'BaselineFontFontWeightSemiBold',
    responsiveFontSize: 'BaselineFontFontSize20',
    responsiveLineHeight: 'BaselineFontFontSize30',
    semanticTag: 'h2',
  },
  h3: {
    fontFamily: 'BaselineFontFontFamilyPoppinsSemiBold',
    fontSize: 'BaselineFontFontSize18',
    lineHeight: 'BaselineFontFontSize28',
    fontWeight: 'BaselineFontFontWeightSemiBold',
    responsiveFontSize: 'BaselineFontFontSize16',
    responsiveLineHeight: 'BaselineFontFontSize24',
    semanticTag: 'h3',
  },
  h4: {
    fontFamily: 'BaselineFontFontFamilyPoppinsSemiBold',
    fontSize: 'BaselineFontFontSize16',
    lineHeight: 'BaselineFontFontSize24',
    fontWeight: 'BaselineFontFontWeightSemiBold',
    responsiveFontSize: 'BaselineFontFontSize14',
    responsiveLineHeight: 'BaselineFontFontSize20',
    semanticTag: 'h4',
  },
  h5: {
    fontFamily: 'BaselineFontFontFamilyPoppinsSemiBold',
    fontSize: 'BaselineFontFontSize14',
    lineHeight: 'BaselineFontFontSize20',
    fontWeight: 'BaselineFontFontWeightSemiBold',
    responsiveFontSize: 'BaselineFontFontSize12',
    responsiveLineHeight: 'BaselineFontFontSize18',
    semanticTag: 'h5',
  },

  // Paragraphs
  p1: {
    fontFamily: 'BaselineFontFontFamilyPoppinsRegular',
    fontSize: 'BaselineFontFontSize18',
    lineHeight: 'BaselineFontFontSize28',
    fontWeight: 'BaselineFontFontWeightRegular',
    responsiveFontSize: 'BaselineFontFontSize16',
    responsiveLineHeight: 'BaselineFontFontSize24',
    semanticTag: 'p',
  },
  p2: {
    fontFamily: 'BaselineFontFontFamilyPoppinsRegular',
    fontSize: 'BaselineFontFontSize16',
    lineHeight: 'BaselineFontFontSize24',
    fontWeight: 'BaselineFontFontWeightRegular',
    responsiveFontSize: 'BaselineFontFontSize14',
    responsiveLineHeight: 'BaselineFontFontSize20',
    semanticTag: 'p',
  },
  p3: {
    fontFamily: 'BaselineFontFontFamilyPoppinsRegular',
    fontSize: 'BaselineFontFontSize14',
    lineHeight: 'BaselineFontFontSize20',
    fontWeight: 'BaselineFontFontWeightRegular',
    responsiveFontSize: 'BaselineFontFontSize12',
    responsiveLineHeight: 'BaselineFontFontSize18',
    semanticTag: 'p',
  },

  // Strong Paragraphs
  p1Strong: {
    fontFamily: 'BaselineFontFontFamilyPoppinsSemiBold',
    fontSize: 'BaselineFontFontSize18',
    lineHeight: 'BaselineFontFontSize28',
    fontWeight: 'BaselineFontFontWeightSemiBold',
    responsiveFontSize: 'BaselineFontFontSize16',
    responsiveLineHeight: 'BaselineFontFontSize24',
    semanticTag: 'p',
  },
  p2Strong: {
    fontFamily: 'BaselineFontFontFamilyPoppinsSemiBold',
    fontSize: 'BaselineFontFontSize16',
    lineHeight: 'BaselineFontFontSize24',
    fontWeight: 'BaselineFontFontWeightSemiBold',
    responsiveFontSize: 'BaselineFontFontSize14',
    responsiveLineHeight: 'BaselineFontFontSize20',
    semanticTag: 'p',
  },
  p3Strong: {
    fontFamily: 'BaselineFontFontFamilyPoppinsSemiBold',
    fontSize: 'BaselineFontFontSize14',
    lineHeight: 'BaselineFontFontSize20',
    fontWeight: 'BaselineFontFontWeightSemiBold',
    responsiveFontSize: 'BaselineFontFontSize12',
    responsiveLineHeight: 'BaselineFontFontSize18',
    semanticTag: 'p',
  },

  // Action Paragraphs
  p1Action: {
    fontFamily: 'BaselineFontFontFamilyPoppinsRegular',
    fontSize: 'BaselineFontFontSize18',
    lineHeight: 'BaselineFontFontSize28',
    fontWeight: 'BaselineFontFontWeightRegular',
    responsiveFontSize: 'BaselineFontFontSize16',
    responsiveLineHeight: 'BaselineFontFontSize24',
    capitaliseText: true,
    semanticTag: 'p',
  },
  p2Action: {
    fontFamily: 'BaselineFontFontFamilyPoppinsRegular',
    fontSize: 'BaselineFontFontSize16',
    lineHeight: 'BaselineFontFontSize24',
    fontWeight: 'BaselineFontFontWeightRegular',
    responsiveFontSize: 'BaselineFontFontSize14',
    responsiveLineHeight: 'BaselineFontFontSize20',
    capitaliseText: true,
    semanticTag: 'p',
  },
  p3Action: {
    fontFamily: 'BaselineFontFontFamilyPoppinsRegular',
    fontSize: 'BaselineFontFontSize14',
    lineHeight: 'BaselineFontFontSize20',
    fontWeight: 'BaselineFontFontWeightRegular',
    responsiveFontSize: 'BaselineFontFontSize12',
    responsiveLineHeight: 'BaselineFontFontSize18',
    capitaliseText: true,
    semanticTag: 'p',
  },

  // Action Paragraphs (Regular)
  p1ActionRegular: {
    fontFamily: 'BaselineFontFontFamilyPoppinsRegular',
    fontSize: 'BaselineFontFontSize18',
    lineHeight: 'BaselineFontFontSize28',
    fontWeight: 'BaselineFontFontWeightRegular',
    responsiveFontSize: 'BaselineFontFontSize16',
    responsiveLineHeight: 'BaselineFontFontSize24',
    capitaliseText: true,
    semanticTag: 'p',
  },
  p2ActionRegular: {
    fontFamily: 'BaselineFontFontFamilyPoppinsRegular',
    fontSize: 'BaselineFontFontSize16',
    lineHeight: 'BaselineFontFontSize24',
    fontWeight: 'BaselineFontFontWeightRegular',
    responsiveFontSize: 'BaselineFontFontSize14',
    responsiveLineHeight: 'BaselineFontFontSize20',
    capitaliseText: true,
    semanticTag: 'p',
  },
  p3ActionRegular: {
    fontFamily: 'BaselineFontFontFamilyPoppinsRegular',
    fontSize: 'BaselineFontFontSize14',
    lineHeight: 'BaselineFontFontSize20',
    fontWeight: 'BaselineFontFontWeightRegular',
    responsiveFontSize: 'BaselineFontFontSize12',
    responsiveLineHeight: 'BaselineFontFontSize18',
    capitaliseText: true,
    semanticTag: 'p',
  },
};
