name: Design System pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  FONTAWESOME_NPM_TOKEN: ${{ secrets.FONTAWESOME_NPM_TOKEN }}
  PUBLISH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_SHARED_PAT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: org-runners
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install --global yarn
      - name: Lint, Format, Test & Build
        run: |
          yarn install
          yarn format:check
          yarn lint:check
          yarn build
          yarn test
          yarn build-storybook
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            storybook-static/**
            packages/**/build/**

  deploy_acceptance:
    needs: build
    runs-on: org-runners
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - name: Deploy to acceptance
        run: |
          npm i -g serverless@3.7.1 serverless-s3-sync@3.0.0
          serverless config credentials --provider aws --key ${{ env.AWS_ACCESS_KEY_ID }} --secret ${{ env.AWS_SECRET_ACCESS_KEY }}
          serverless deploy -s acceptance

  deploy_production:
    needs: deploy_acceptance
    runs-on: org-runners
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.PUBLISH_PACKAGES_PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - name: Setup git push permissions
        run: |
          git config --global user.name 'NewcrossGitHubSA'
          git config --global user.email 'github-actions@newcrosshealthcare.com'
      - name: Deploy to production
        run: |
          npm i -g serverless@3.7.1 serverless-s3-sync@3.0.0 lerna@4.0.0 husky@7.0.0
          serverless config credentials --provider aws --key ${{ env.AWS_ACCESS_KEY_ID }} --secret ${{ env.AWS_SECRET_ACCESS_KEY }}
          serverless deploy -s production
          lerna publish --yes
