name: PR pipeline
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/deps-setup
        with:
          github_packages_token: ${{ secrets.GH_PACKAGES_SHARED_PAT }}
          fontawesome_npm_token: ${{ secrets.FONTAWESOME_NPM_TOKEN }}
      - name: Lint, Format & Test
        run: |
          yarn format:check
          yarn lint:check
          yarn build
          yarn typecheck
          git checkout main
          git checkout ${GITHUB_HEAD_REF}
          npm run test --branch=main
