name: PR pipeline
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  FONTAWESOME_NPM_TOKEN: ${{ secrets.FONTAWESOME_NPM_TOKEN }}

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Lint, Format & Test
        run: |
          yarn install
          yarn format:check
          yarn lint:check
          yarn build
          git checkout main
          git checkout ${GITHUB_HEAD_REF}
          npm run test --branch=main
          
